version: '3.8'

services:
  # Django Web 服務
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  # PostgreSQL 資料庫服務
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  # Redis 服務 (Celery Broker)
  redis:
    image: redis:6-alpine

  # Celery Worker 服務
  worker:
    build: .
    command: celery -A orange_juice worker -l info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: