# Generated by Django 5.2.4 on 2025-08-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='session_id',
            field=models.CharField(blank=True, help_text='登入後從 OJ 取得的 session ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_USE', 'In Use'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20),
        ),
    ]
