# Generated by Django 5.2.4 on 2025-08-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_account_session_id_alter_account_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='session_id',
        ),
    ]
