# Generated by Django 5.2.5 on 2025-08-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_remove_account_session_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrawlTask',
            new_name='CrawlTestCasesTask',
        ),
        migrations.AlterField(
            model_name='crawlersource',
            name='code',
            field=models.JSONField(help_text='完整的爬蟲原始碼，以 JSON 格式儲存'),
        ),
    ]
