# Generated by Django 5.2.5 on 2025-08-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_rename_crawltask_crawltestcasestask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawltestcasestask',
            name='footer_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crawltestcasestask',
            name='header_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
