# Generated by Django 5.2.5 on 2025-08-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_crawltestcasestask_footer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawltestcasestask',
            name='crawler_state',
            field=models.JSONField(blank=True, help_text='儲存 CrawlerCore 的執行狀態，以便中斷後恢復', null=True),
        ),
    ]
