# Generated by Django 5.2.5 on 2025-08-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_crawltestcasestask_crawler_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PAUSED', 'Paused')], default='PENDING', max_length=20),
        ),
    ]
